### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by CodingSlant123** [Expertcoderz/EC-Autoclicker#6]
Make it so that there is another version without a GUI where i can customize the features in the code in areas clearly highlighted. Also, make it so that you can make the hotkey toggle so if my hotkey was F2 i could use that to on and off the autoclicker. Please and thank you!
I don't know how to do this and there are many reasons for no GUI.

**Comment by Expertcoderz** [comment]
Thanks for your suggestons! I've just implemented the changes and will be publishing a new release shortly. For the "version without a GUI", it's simpler to just add a command-line option `/profile <profile name>` to make the autoclicker run based on a predefined profile's configuration. This way you can customize settings via the GUI first, save it as a profile and then run it from the CLI.

**Comment by CodingSlant123** [comment]
Hello! Thank you for the reply. Is it possible you could make a small documentation for the /profile <name> command? Or did I understand you wrong.
Thanks :)

**Comment by Expertcoderz** [comment]
> Hello! Thank you for the reply. Is it possible you could make a small documentation for the /profile command? Or did I understand you wrong. Thanks :)

The [new release](https://github.com/Expertcoderz/EC-Autoclicker/releases/tag/v1.2.0) is now out and the [documentation](https://github.com/Expertcoderz/EC-Autoclicker/tree/v1.2.0?tab=readme-ov-file#headless-operation) for running without a GUI has been added.

**Comment by CodingSlant123** [comment]
Hi! Just a quick question, how would i use the no-GUI form in the AHK version? My school laptop can't open EXE files and when it does norton just deletes compiled AHK scripts....

**Comment by Expertcoderz** [comment]
> Hi! Just a quick question, how would i use the no-GUI form in the AHK version? My school laptop can't open EXE files and when it does norton just deletes compiled AHK scripts....

You'll first need to have [AutoHotkey v2](https://www.autohotkey.com/download/ahk-v2.exe) installed. Once you do, just run `<path to EC-Autoclicker.ahk> /profile <profile name>` (depending on where you put the script file)  in Command Prompt or the Win+R dialog:
![image](https://github.com/Expertcoderz/EC-Autoclicker/assets/81153405/e7c35c27-b9b1-4303-848b-358631749ddd)

Though, if you can't run EXE files chances are you wouldn't have been able to install AHK in the first place to run the script.

**Comment by CodingSlant123** [comment]
That was before my grades went into the void :)

**Comment by Casmyx** [comment]
I may or may not have joined just to request this but can you fix where in the no GUI mode 'Note that, in headless mode, any hotkeys assigned the Stop Autoclicker action will function equivalently to Close Autoclicker when triggered.' is fixed like it beats the point for the toggle thing. Please and thank you.

**Comment by Casmyx** [comment]
Can I make the profile with the EXE/.ahk and later run it headless without having to open the file and press run headless, like from the Run application from before?

**Comment by Casmyx** [comment]
I'm still gonna have  to  open it to collapse  it to tray though
Or is that unavoidable?
